### ISSUE TITLE
Projeto desorganizado!

### ISSUE THREAD

**Issue by olivatooo** [UncreativeGames/captain-cleiton#10]
Precisamos organizar a estruturação das pastas.
* Onde cada classe vai ficar?
* Vamos separar por funções? Exemplo
  * Pasta só com `game engine`
  * Pasta só com `geração de mapa`

**Seria interessante realizar essa organização o quanto antes**

**Comment by igmagollo** [comment]
### Sugestão de organização:
* Duas pastas principais, sendo estas "include" para os headers e "src" para as implementações
  * Cada uma destas pastas poderá conter mais pastas separando em módulos como seus exemplos:
    * ```game_engine```
    * ```funcionalidades```

##### Organização dos módulos a definir.

**Comment by vitoor-s** [comment]
Em geral os projetos são organizados em:
```bin/```
```include/```
```src/```
```media/```
Acredito que essa seja uma divisão recomendável, assim como o Igor falou. Mais internamente podemos separar melhor, mas acho que essa seria a primeira divisão.

**Comment by igmagollo** [comment]
Organizado em #20
