### ISSUE TITLE
O que são inimigos em uma matriz?

### ISSUE THREAD

**Issue by olivatooo** [UncreativeGames/captain-cleiton#16]
Precisa-se definir o que vão ser inimigos. Exemplo:
 * Será um caractere?
 * Será um número?
 * Será um objeto?

Após difinir isso pode-se continuar com #15

**Comment by igmagollo** [comment]
Bom, acredito que podemos definir de qualquer forma.

Acredito que um caracter por enquanto é o ideal, pois ainda não temos inimigos prontos e podemos instancia-los utilizando este parametro .
