### ISSUE TITLE
Divisão do gerenciamento do jogo em modulos

### ISSUE THREAD

**Issue by igmagollo** [UncreativeGames/captain-cleiton#17]
## Sugestão para divisão do gerenciamento do jogo em modulos
Os modulos que sugiro são os seguintes:
* DrawingModule.hpp
    * Classe responsável pela exibição de tudo.
* ColisionModule.hpp
    * Classe responsável por controlar as colisões dos objetos do jogo.
* MapModule.hpp
    * Classe responsável por alterar as listas de objetos do mapa, como por exemplo, excluir as coisas do mapa anterior e carregar as coisas do mapa atual ao trocar de sala.

Aberto à sugestões para novos modulos e modificações na ideia.
Posteriormente novos moduloes surgiram, como um modulo de audio. Até lá, outras classes deverão ser alteradas.

**Comment by olivatooo** [comment]
Acredito que podemos adicionar e remover módulos do jogo ao nosso gosto. Gostaria de ficar encarregado do `MapModule.hpp `

**Comment by igmagollo** [comment]
Bom, após codar um pouco do DrawingModule percebi que algumas alterações precisão ser feitas no Listaestatica.hpp.
Abrirei um novo issue.
