### ISSUE TITLE
Colisão com perímetro perfeita

### ISSUE THREAD

**Issue by igmagollo** [UncreativeGames/captain-cleiton#39]
* Sugestão de colisão para principalmente objetos retangulares como a parede.
* Fácil de implementar
  * Consiste em uma lista de pontos do perímetro que se comportam como círculos com raio 0
  * Pouco otimizada pois objetos devem verificar a colisão com todos os pontos do perímetro
    * Pode ser melhor otimizada com o por exemplo com um circulo maior que contém todos os pontos, caso o objeto que deseja verificar colisão nao esteja no círculo não é necessario verificar colisão com os pontos
## Motivação:
* É mais fácil controlar a colisão de um retângulo com esta implementação pois cada ponto manda facilmente a hitBox inimiga para a posição mais imediata tangenciando a si mesmo.
* Já um retângulo em si existem muitos casos ambíguos onde não sabemos ao certo "para qual direção mandar o objeto".

**Comment by vitoor-s** [comment]
Como você determina o raio adequado para cada sprite?

**Comment by igmagollo** [comment]
### Interessante ressaltar que é possível otimizar bem essa colisão além de que conseguimos fazer qualquer formato

**Comment by igmagollo** [comment]
* wall será fetia com essa colisão

**Comment by igmagollo** [comment]
Hard

**Comment by igmagollo** [comment]
#47 Resolvido em partes!
