### ISSUE TITLE
Como posso executar?

### ISSUE THREAD

**Issue by LorhanSohaky** [UncreativeGames/captain-cleiton#64]
Não encontrei nenhum Makefile

**Comment by olivatooo** [comment]
Atualmente não temos um jogo completo, temos um makefile padrão para testes em: [Jogo](https://github.com/UncreativeGames/captain-cleiton/tree/master/examples/DrawingModule_exemplo_2).
Mas como os sprites do nosso jogo possuem copyright, você precisa fornecer seus próprios sprites ou aguardar o lançamento oficial do jogo e comprá-lo

**Comment by olivatooo** [comment]
Agora makefile está no root do projeto, mas vale a pena dar uma conferida nesta issue #69
