### ISSUE TITLE
Geração de `Floor`

### ISSUE THREAD

**Issue by olivatooo** [UncreativeGames/captain-cleiton#7]
#### Necessário:
* Navegação por grafos
  * Dúvidas com @vitoor-s

**Comment by igmagollo** [comment]
### O que é Floor?

**Comment by vitoor-s** [comment]
Acho que seria o nível, tem alguma dúvida por enquanto?

**Comment by olivatooo** [comment]
Issue fechada pois não está específicada. Uma futura issue será aberta, ou apenas um pull request
