### ISSUE TITLE
Como vamos organizar os #include?

### ISSUE THREAD

**Issue by olivatooo** [UncreativeGames/captain-cleiton#9]
É uma boa prática manter por exemplo ```#include <iostream>``` em vários arquivos diferentes?

**Comment by igmagollo** [comment]
Acredito que podemos manter header e implementação em pastas diferentes.
Não sei se é exatamente uma boa prática, mas já vi algumas vezes.

**Comment by vitoor-s** [comment]
#include<bits/stdc++.h> :P

**Comment by vitoor-s** [comment]
brincadeiras à parte, acho que é 'bonito' deixar headers separados da implementação, vou pesquisar mais sobre isso, talvez dê para deixar todos os headers num arquivo.

**Comment by olivatooo** [comment]
Issue melhorada em #34
